server:
  port: 8003
  address: 0.0.0.0
  servlet:
    context-path: /family/diary/api

spring:
  application:
    name: person-website
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    com.qcloud.cos.http.DefaultCosHttpClient: WARN

wechat:
  app-id: ${WECHAT_APP_ID}
  app-secret: ${WECHAT_APP_SECRET}
  code-to-session-url: https://api.weixin.qq.com/sns/jscode2session

tencent-cloud:
  app-id: 1259817492
  api-secret-id: ${TENCENT_CLOUD_API_SECRET_ID}
  api-secret-key: ${TENCENT_CLOUD_API_SECRET_KEY}
  cos:
    bucket: jihao-family-1259817492
    region: ap-guangzhou
    host: cos.jihao-family.com
    default-host: jihao-family-1259817492.cos.ap-guangzhou.myqcloud.com